language: r
cache: packages

r:
#  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
    - gs

packages:
  - covr

notifications:
  email:
    on_success: change
    on_failure: change

## Only run covr on release
after_success:
  - Rscript -e "if(length(grep('1\$', ${TRAVIS_JOB_NUMBER}))) covr::codecov()";


